# Generated by Django 4.1.3 on 2023-06-02 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Categoria')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre de Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Id Producto')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda.categoria', verbose_name='Categoria')),
            ],
        ),
    ]
