# Generated by Django 5.1.5 on 2025-02-02 02:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0005_boleta_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='producto',
            name='destacado',
            field=models.BooleanField(default=False, verbose_name='Producto destacado'),
        ),
        migrations.AddField(
            model_name='producto',
            name='especificaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Especificaciones'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de creación'),
        ),
    ]
