# Generated by Django 5.1.5 on 2025-07-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0006_producto_descripcion_producto_destacado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, storage='django_storage_supabase.supabase', upload_to='imagenes', verbose_name='Imagen'),
        ),
    ]
