# Generated by Django 5.1.5 on 2025-07-21 20:30

import django_storage_supabase.supabase
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0007_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, storage=django_storage_supabase.supabase.SupabaseStorage(), upload_to='imagenes', verbose_name='Imagen'),
        ),
    ]
